version: '2.2'
services:
  db :
    image: mysql/mysql-server
    container_name: db-container
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_DATABASE=${DB_NAME}"
    networks:
      - leboncoin
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 5s
      retries: 10

  app :
    build : .
    container_name: app-container
    volumes:
      - ".:/app"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "8000:8000"
    networks:
      - leboncoin

networks:
  leboncoin:
    driver: bridge